"""Fix TelecomResults

Revision ID: 376c9903aa23
Revises: 8618214987e4
Create Date: 2024-05-24 16:55:08.472884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376c9903aa23'
down_revision: Union[str, None] = '8618214987e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_info_result_id_fkey', 'task_info', type_='foreignkey')
    op.drop_column('task_info', 'result_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_info', sa.Column('result_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('task_info_result_id_fkey', 'task_info', 'telecom_results', ['result_id'], ['id'])
    # ### end Alembic commands ###
