"""Add TelecomResults and TaskInfo models

Revision ID: 8618214987e4
Revises: 8a49af74aa0a
Create Date: 2024-05-24 16:38:37.330567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8618214987e4'
down_revision: Union[str, None] = '8a49af74aa0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telecom_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('result_type', sa.String(), nullable=False),
    sa.Column('result_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telecom_results_id'), 'telecom_results', ['id'], unique=False)
    op.create_table('task_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['telecom_results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_info_id'), 'task_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_info_id'), table_name='task_info')
    op.drop_table('task_info')
    op.drop_index(op.f('ix_telecom_results_id'), table_name='telecom_results')
    op.drop_table('telecom_results')
    # ### end Alembic commands ###
